apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wouter
  name: wouter
spec:
  containers:
  - image: nginx
    name: wouter
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
